# This file was generated by GoReleaser. DO NOT EDIT.
cask "ytglean" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "cb07b463112070531029494c5fba80568a2bab3bdac6e3d487a817be4b4b5e21"
      url "https://github.com/Crymfox/YTGlean/releases/download/v#{version}/ytglean_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d8cb42dfb3601f45d51b5e712528d3bfdd94080bc94e9e2a487ab164f6caefd7"
      url "https://github.com/Crymfox/YTGlean/releases/download/v#{version}/ytglean_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "83491f33f8bf22247fc629acc04a48c995a92ff114fba08122b3415773f90de5"
      url "https://github.com/Crymfox/YTGlean/releases/download/v#{version}/ytglean_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c586d1cd17c2bf381f1ab521b32f309f058814b6013355df7b11d763a1531625"
      url "https://github.com/Crymfox/YTGlean/releases/download/v#{version}/ytglean_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ytglean"
  desc "Glean transcripts from YouTube channels, summarize via LLM, and serve them over MCP"
  homepage "https://github.com/Crymfox/YTGlean"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ytglean"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ytglean"]
    end
  end

  # No zap stanza required

end
