# This file was generated by GoReleaser. DO NOT EDIT.
cask "ytglean" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "47e021840c258b070a19ffea21be701760019dc0c2dbf9a0b25d95f5a97edccc"
      url "https://github.com/Crymfox/YTGlean/releases/download/v#{version}/ytglean_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0e56c76bcd3426724827601a37b1afc3a6185fe03d7bae6f3b41015e0d152970"
      url "https://github.com/Crymfox/YTGlean/releases/download/v#{version}/ytglean_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "23f9582131f5c1a670d183109093abb7d6b9352bb8b3cc365b4905b73b258ae4"
      url "https://github.com/Crymfox/YTGlean/releases/download/v#{version}/ytglean_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3a110c3afc176cb8bd86c1e26e16ed31a7c887f04dd47113ef6e7961d50aee01"
      url "https://github.com/Crymfox/YTGlean/releases/download/v#{version}/ytglean_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ytglean"
  desc "Glean transcripts from YouTube channels, summarize via LLM, and serve them over MCP"
  homepage "https://github.com/Crymfox/YTGlean"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ytglean"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ytglean"]
    end
  end

  # No zap stanza required

end
