# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nac < Formula
  desc "n8n As Code - Manage n8n workflows and credentials as version-controlled files."
  homepage "https://github.com/crymfox/nac"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Crymfox/nac/releases/download/v0.1.2/nac_Darwin_x86_64.tar.gz"
      sha256 "b4ca9f26f7ca5738e4d834969df01bced5ed902c72d3792f73e7697dadc0ca51"

      define_method(:install) do
        bin.install "nac"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Crymfox/nac/releases/download/v0.1.2/nac_Darwin_arm64.tar.gz"
      sha256 "262db91313b131f0852baf26a7fe78a3c72c2acdc1de6bacfe628423cceaa23a"

      define_method(:install) do
        bin.install "nac"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Crymfox/nac/releases/download/v0.1.2/nac_Linux_x86_64.tar.gz"
      sha256 "77e6adb7c06903ea5c2955771dbaf460d867fcc1e15e061d1997f6167edbc336"
      define_method(:install) do
        bin.install "nac"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Crymfox/nac/releases/download/v0.1.2/nac_Linux_arm64.tar.gz"
      sha256 "9008e88c7a74d88d896ffd366fe66068473076cea9cc31903b2267d47c36a42f"
      define_method(:install) do
        bin.install "nac"
      end
    end
  end
end
